### ISSUE TITLE
댓글입력창을 portfolioView 에 넣어야하는데... 

### ISSUE THREAD

**Issue by YunaJjo** [jsooshi/icu#6]
제가 portfolioView 실행하면 다 깨져서 뜨는데 아마 뭔가 부트스트랩이라던가 설정이 없어서 그런데 알려주세요... 혹은 댓글 입력창만  portfolioView 안에 textfield 로 넣고 싶어효... 아영님 도와주세여.................

**Comment by afterup** [comment]
부트스트랩 설정이 ajax 연결전이어서 제대로 안돼있을거에요 ㅜㅜ 
일단 댓글만 따로 뷰 만들어서 진행해주세요!
아래소스대로 만드시면 될것같슴다
```
    [댓글]
    <img src="" class="rounded-circle" style="width:20%; display:inline;">
    <form action="" method="POST">
        <input type="text">
        <input type="button" value="등록" class="btn btn-primary">
    </form>
    <div>
        <!-- 댓글 내용-->
    </div>

```

**Comment by YunaJjo** [comment]
오 그럼 그 뷰에 보니까 [댓글] 요케 되있는데 있던데 거기에 붙여넣으면 되죵?? 알겠음다 해볼게요 근데 왜 안오삼
